### ISSUE TITLE
smult_curve25519_donna_c64 Doesn't build on RHEL5 (gcc-Version 4.1.2 20080704 (Red Hat 4.1.2-54))

### ISSUE THREAD

**Issue by Asmod4n** [jedisct1/libsodium#71]
This is with 0.4.2
only used ./configure && make and got this result.

```
  CC       libsodium_la-smult_curve25519_donna_c64.lo
crypto_scalarmult/curve25519/donna_c64/smult_curve25519_donna_c64.c: In function 'crypto_scalarmult_curve25519':
crypto_scalarmult/curve25519/donna_c64/smult_curve25519_donna_c64.c:424: error: unrecognizable insn:
(insn 9952 6932 9953 20 crypto_scalarmult/curve25519/donna_c64/smult_curve25519_donna_c64.c:236 (parallel [
            (set (reg:CC 17 flags)
                (unspec:CC [
                        (reg:DI 39 r10 [orig:375 t$0.844 ] [375])
                        (const_int 2251799813685229 [0x7ffffffffffed])
                    ] 24))
            (set (reg:DI 39 r10 [orig:375 t$0.844 ] [375])
                (plus:DI (reg:DI 39 r10 [orig:375 t$0.844 ] [375])
                    (const_int 2251799813685229 [0x7ffffffffffed])))
        ]) -1 (nil)
    (nil))
crypto_scalarmult/curve25519/donna_c64/smult_curve25519_donna_c64.c:424: internal compiler error: in extract_insn, at recog.c:2084
```
