### ISSUE TITLE
[.Net - Sodium.Core] building for linux-musl-arm64

### ISSUE THREAD

**Issue by bfren** [jedisct1/libsodium#1173]
I posted an issue over on [Sodium.Core](https://github.com/ektrah/libsodium-core/issues/82) and @ektrah suggested a PR over here.

I'd like to be able to use it in a project hosted in an Alpine Docker image on a Raspberry Pi 4 - hence there needs to be a build of libsodium that supports linux-musl-arm64.  From the rest of the .NET Package workflow I've added what I think needs to be done to create the right build, but I know absolutely nothing about building C so I could be wrong.

The build workflow succeeds, so it's definitely building something... however the workflow fails to build the test environment for arm64 due to a hash failure.

I'm happy to help if I can, but I realise this is outside my knowledge.  If it's not possible to do that would be helpful to know in itself.

**Comment by jedisct1** [comment]
Hi,

Can you clarify what the hash failure is? Is a particular test failing?

**Comment by jedisct1** [comment]
According to [1](https://unix.stackexchange.com/questions/116641/how-do-you-fix-apt-get-update-hash-sum-mismatch) and [2](https://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error), the solution is:

```sh
sudo rm -rf /var/lib/apt/lists/*
sudo apt-get update
```

**Comment by bfren** [comment]
OK the issue was actually [this](https://askubuntu.com/questions/1235914/hash-sum-mismatch-error-due-to-identical-sha1-and-md5-but-different-sha256#1242739) so I've added that to the .NET Package workflow and now everything works.

I can't quite figure out how the test binaries action works to know if there's anything I need to do there to make sure the new binary is tested as well?  I see how it tests different archs but can't see how it tests musl / glibc etc - do the `qemu` packages handle that?

**Comment by bfren** [comment]
Don't wish to nag but... Any chance 1.0.18.3 could be released?

**Comment by jedisct1** [comment]
But does the `linux-musl-arm64` library actually work?

In the CI, the `make check` command is still disabled, so we would be releasing it without any testing.

**Comment by jedisct1** [comment]
By the way, these packages are still built on Ubuntu Xenial, that reached end-of-line in April 2021.

**Comment by bfren** [comment]
I'm happy to help with testing - are there any docs / instructions for running the tests?

**Comment by jedisct1** [comment]
That's what the `make check` command does, but it should be done on CI.

Or if you are using Zig to compile libsodium, go to `zig-out/bin` and run `./run.sh`.

**Comment by bfren** [comment]
In the dotnet-core.yml file, under the new build-linux-musl-arm64 job, there is `make check` [line](https://github.com/jedisct1/libsodium/blob/03137a5817d1ed867976cfe55e86a1ee9202d8d7/.github/workflows/dotnet-core.yml#L179).  Do you mean something needs to go in ci.yml as well?

**Comment by bfren** [comment]
Sorry if I've spammed anyone, I've made a right dog's dinner of attempting to re-enable make check on that platform to see what happens - I'm nearly there and will post back once I've got some results.

**Comment by bfren** [comment]
OK so there are loads of [failures](https://github.com/bfren/libsodium/actions/runs/3541039183/jobs/5944812477#step:7:201).

```
Makefile:1784: recipe for target 'test-suite.log' failed
make[4]: Leaving directory '/__w/libsodium/libsodium/test/default'
make[3]: *** [check-TESTS] Error 2
Makefile:1890: recipe for target 'check-TESTS' failed
make[3]: Leaving directory '/__w/libsodium/libsodium/test/default'
make[2]: *** [check-am] Error 2
Makefile:2497: recipe for target 'check-am' failed
make[2]: Leaving directory '/__w/libsodium/libsodium/test/default'
make[1]: *** [check-recursive] Error 1
Makefile:411: recipe for target 'check-recursive' failed
make[1]: Leaving directory '/__w/libsodium/libsodium/test'
make: *** [check-recursive] Error 1
Makefile:523: recipe for target 'check-recursive' failed
Error: Process completed with exit code 2.
```

To be honest it looks like everything is failing which suggests to me something is wrong with the build environment, but it looks identical to the (working) glibc-arm job, just with a different target architecutre.

**Comment by jedisct1** [comment]
That should be fixed now :)

I'm still worried about using Ubuntu 16.04. This is going to break soon.

**Comment by bfren** [comment]
OK, I'll do another fork and see if the whole thing works / builds on Ubuntu 22.04 - but that's probably for another Issue!

**Comment by jedisct1** [comment]
It does work. But the issue is that CentOS 7, released 8 years ago, is still supported until 2024.

And using a more recent Ubuntu version gives a library that doesn't work on that antique system.

This is annoying. Especially since the performance we get is not on par with what we would get by using a more recent compiler, and that affects recent systems, too.

**Comment by ektrah** [comment]
As I understand it, the only thing holding us back is that CentOS 7 uses an ancient glibc, which causes the ["Undefined reference to mempcy@GLIBC_2.14" problem](https://stackoverflow.com/a/54815372) if libsodium is compiled against a more recent glibc.

Maybe the build process could be modified so that the dynamic linker will look for the `memcpy@GLIBC_2.2.5` symbol in glibc instead of `mempcy@GLIBC_2.14` when loading libsodium? Then, I believe, it should be possible to compile libsodium on a system with the latest glibc and still have the binary work on systems with an ancient glibc.

**Comment by jedisct1** [comment]
@ektrah I tried that -- The library built on Ubuntu 22.04 then ran on CentOS 7... but not on Ubuntu 22.04 :0 https://github.com/jedisct1/libsodium/actions/runs/3547737841/jobs/5958260164

**Comment by ektrah** [comment]
It seems the test on CentOS 7 was canceled before it actually ran... Could you re-run with [`fail-fast: false`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) and the [`LD_DEBUG` environment variable set to `all`](https://man7.org/linux/man-pages/man8/ld.so.8.html)?

**Comment by jedisct1** [comment]
Sure!

The Ubuntu version is not a showstopper to release new packages, though. At least we now have all the targets properly tested.

**Comment by bfren** [comment]
Well personally I'd be really pleased if 1.0.18.3 were released so Sodium.Core can be updated and I can run some stuff on my Raspberry Pi 4!

**Comment by ektrah** [comment]
Btw, where did @bfren's [version bump to 1.0.18.3](https://github.com/jedisct1/libsodium/pull/1174/commits/38ed9afbcfb9051ee78e7d9dfc0d2874721a55ed) go? The GitHub Actions artifact still says 1.0.18.2.

**Comment by bfren** [comment]
Did it get clobbered by a merge from master or something?  I'll happily add it back 😂

**Comment by jedisct1** [comment]
Probably clobbered by a copy from `stable` to `master`.

I'm gonna add it back.

**Comment by jedisct1** [comment]
Closing since the discussing continues in the other issue :)

Thanks a lot for your help!
