### ISSUE TITLE
aarch64 build fails after updating from 1.0.18 to 1.0.19

### ISSUE THREAD

**Issue by Alexander-Wilms** [jedisct1/libsodium#1313]
The Octave Flatpak package uses libsodium and version 1.0.18 was built successfully:

Cf. CI of latest commit to https://github.com/flathub/org.octave.Octave

But after updating libsodium, the build failed:

https://github.com/flathub/org.octave.Octave/pull/307/files

```
crypto_aead/aegis128l/aegis128l_armcrypto.c:23:9: error: pragma or attribute ‘target("neon")’ is not valid
   23 | #pragma GCC target("neon,crypto,aes")
      |         ^~~

crypto_aead/aegis256/aegis256_armcrypto.c:23:9: error: pragma or attribute ‘target("neon")’ is not valid
   23 | #pragma GCC target("neon,crypto,aes")
      |         ^~~
```

See https://buildbot.flathub.org/#/builders/6/builds/65343 for a complete log, which I've attached as well: [stdio.txt](https://github.com/jedisct1/libsodium/files/12597763/stdio.txt)

**Comment by cschug** [comment]
Had the same issue on aarch64 and can confirm that [fb4533b](https://github.com/jedisct1/libsodium/commit/fb4533b0a941b3a5b1db5687d1b008a5853d1f29) fixes the issue, thanks a lot!

**Comment by jedisct1** [comment]
Thank you!

The tag has been updated to the current `stable`, that includes that fix, thanks!
